<a href="https://colab.research.google.com/github/ferdade/hinerds/blob/main/Regressao_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regressão Linear

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_excel("/content/drive/MyDrive/PrograMaria/analise_dados_mod7_(1).xlsx")

In [ ]:
dados.head()

,ID,IDADE,FAIXA IDADE,GENERO,COR/RACA/ETNIA,PCD,EXPERIENCIA_PROFISSIONAL_PREJUDICADA,ASPECTOS_PREJUDICADOS,VIVE_NO_BRASIL,ESTADO ONDE MORA,...,Você pretende mudar de emprego nos próximos 6 meses?,Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?,Atualmente qual a sua forma de trabalho?,Qual a forma de trabalho ideal para você?,Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?,Sua empresa passu por Layoff em 2022?,Atuacao,Quais das linguagens listadas abaixo você utiliza no trabalho?,EM_BUSCA,ABERTO_OPORTUNIDADES
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,39.0,35-39,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,NaN,True,Distrito Federal (DF),...,Não estou buscando e não pretendo mudar de emp...,Benefícios,Modelo 100% presencial,Modelo híbrido com dias fixos de trabalho pres...,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Engenharia de Dados,SQL,0.0,0.0
1,zzls2oftfn9law393oezzls2ofhvfpzd,32.0,30-34,Masculino,Parda,Não,"Sim, acredito que a minha a experiência profis...",Aprovação em processos seletivos/entrevistas,True,Pará (PA),...,Estou em busca de oportunidades dentro ou fora...,"Remuneração/Salário, Plano de carreira e oport...",Modelo 100% presencial,Modelo híbrido flexível (o funcionário tem lib...,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Gestor,NaN,1.0,0.0
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,53.0,50-54,Masculino,Branca,Não,NaN,NaN,True,Distrito Federal (DF),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Flexibilidade de trabalho...",Modelo híbrido com dias fixos de trabalho pres...,Modelo híbrido flexível (o funcionário tem lib...,Vou procurar outra oportunidade no modelo híbr...,Não ocorreram layoffs/demissões em massa na em...,desenvolve modelos preditivos e algoritmos de ...,1,0.0,1.0
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,27.0,25-29,Masculino,Branca,Não,NaN,NaN,True,Minas Gerais (MG),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Flexibilidade de trabalho...",Modelo híbrido flexível (o funcionário tem lib...,Modelo híbrido flexível (o funcionário tem lib...,Vou procurar outra oportunidade no modelo híbr...,Não ocorreram layoffs/demissões em massa na em...,desenvolve modelos preditivos e algoritmos de ...,0,0.0,1.0
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,46.0,45-49,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,NaN,True,Pará (PA),...,"Não estou buscando, mas me considero aberto a ...","Remuneração/Salário, Oportunidade de aprendiza...",Modelo 100% presencial,Modelo 100% presencial,Vou aceitar e retornar ao modelo 100% presencial,Não ocorreram layoffs/demissões em massa na em...,Outra atuação,SQL,0.0,1.0

In [ ]:
dados.columns

Index(['ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA', 'PCD',
       'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'UF ONDE MORA',
       'REGIAO ONDE MORA', 'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM',
       'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO', 'NOVO_NIVEL', 'NIVEL_Júnior', 'NIVEL_Pleno', 'NIVEL_Sênior',
       'GEARACAO', 'Quanto tempo de experiência na área de dados você tem?',
       'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?',
       'Você está satisfeito na sua empresa atual?',
       'Qual o principal motivo da sua insatisfação com a empresa atual?',
       'Você participou de entrevistas de emprego nos últimos 6 meses?',
       'Você pretende mudar de emprego nos próximos 6 meses?',
       'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?',
       'Atualmente qual a sua forma de trabalho?',
       'Qual a forma de trabalho ideal para você?',
       'Caso sua empresa decida pelo modelo 100% presencial qual será sua atitude?',
       'Sua empresa passu por Layoff em 2022?', 'Atuacao',
       'Quais das linguagens listadas abaixo você utiliza no trabalho?',
       'EM_BUSCA', 'ABERTO_OPORTUNIDADES'],
      dtype='object')

In [ ]:
dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?'].value_counts()

QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?
Empregado (CLT)                                                    2762
Empreendedor ou Empregado (CNPJ)                                    410
Desempregado, buscando recolocação                                  350
Estagiário                                                          188
Servidor Público                                                    156
Trabalho na área Acadêmica/Pesquisador                               86
Somente Estudante (graduação)                                        82
Vivo no Brasil e trabalho remoto para empresa de fora do Brasil      69
Vivo fora do Brasil e trabalho para empresa de fora do Brasil        46
Somente Estudante (pós-graduação)                                    44
Freelancer                                                           39
Prefiro não informar                                                 24
Desempregado e não estou buscando recolocação                        15
Name: count, dtype: int64

In [ ]:
dados = dados[dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?']=='Empregado (CLT)']

In [ ]:
dados['QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?'].value_counts()

QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?
Empregado (CLT)    2762
Name: count, dtype: int64

In [ ]:
dados['COR/RACA/ETNIA'].value_counts()

COR/RACA/ETNIA
Branca                  1805
Parda                    661
Preta                    181
Amarela                   85
Prefiro não informar      16
Outra                     10
Indígena                   4
Name: count, dtype: int64

In [ ]:
lista_retirar = ['Prefiro não informar','Outra','Indígena']

In [ ]:
dados = dados[~dados['COR/RACA/ETNIA'].isin(lista_retirar)]

In [ ]:
dados['nao_branca'] = dados['COR/RACA/ETNIA'].apply(lambda x: 1 if x != 'Branca' else 0)

In [ ]:
dados['Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?'].value_counts()

Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?
Não tive experiência na área de TI/Engenharia de Software antes de começar a trabalhar na área de dados    1605
Menos de 1 ano                                                                                              734
de 1 a 2 anos                                                                                               468
de 3 a 4 anos                                                                                               306
Mais de 10 anos                                                                                             265
de 5 a 6 anos                                                                                               160
de 7 a 10 anos                                                                                              156
Name: count, dtype: int64

In [ ]:
dados['Tempo de expêriencia'] = dados['Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?'].str.extract(r'(\d+)')

In [ ]:
dados['Tempo de expêriencia']

0         7
1         1
2        10
3       NaN
4        10
       ...
4266      7
4267    NaN
4268    NaN
4269    NaN
4270    NaN
Name: Tempo de expêriencia, Length: 4271, dtype: object

In [ ]:
dados['NUMERO DE FUNCIONARIOS'].value_counts()

NUMERO DE FUNCIONARIOS
Acima de 3000     1525
de 101 a 500       703
de 1001 a 3000     450
de 501 a 1000      344
de 11 a 50         252
de 51 a 100        240
de 1 a 5           116
de 6 a 10           64
Name: count, dtype: int64

In [ ]:
dados['NUMERO DE FUNCIONARIOS'] = dados['NUMERO DE FUNCIONARIOS'].str.replace('.','')

In [ ]:
dados['NUMERO DE FUNCIONARIOS'] = dados['NUMERO DE FUNCIONARIOS'].str.extract(r'(\d+)')

In [ ]:
dados['NUMERO DE FUNCIONARIOS'].value_counts()

NUMERO DE FUNCIONARIOS
3000    1525
101      703
1001     450
501      344
11       252
51       240
1        116
6         64
Name: count, dtype: int64

In [ ]:
dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].value_counts()

Qual o principal motivo da sua insatisfação com a empresa atual?
Gostaria de trabalhar em em outra área de atuação                                                                                                           112
Salário atual não corresponde ao mercado                                                                                                                     76
Falta de oportunidade de crescimento no emprego atual                                                                                                        67
Falta de maturidade analítica na empresa                                                                                                                     64
Falta de oportunidade de crescimento no emprego atual, Salário atual não corresponde ao mercado, Falta de maturidade analítica na empresa                    31
                                                                                                                                                           ...
Falta de organização nos processos internos                                                                                                                   1
Gostaria de receber mais benefícios, O clima de trabalho/ambiente não é bom, Falta de oportunidade de crescimento no emprego atual                            1
Gostaria de receber mais benefícios, Falta de oportunidade de crescimento no emprego atual, O clima de trabalho/ambiente não é bom                            1
Não tenho uma boa relação com meu líder/gestor, Falta de oportunidade de crescimento no emprego atual, Gostaria de trabalhar em em outra área de atuação      1
Gostaria de receber mais benefícios, Gostaria de aumento no salario em comparação ao exteriro                                                                 1
Name: count, Length: 221, dtype: int64

In [ ]:
dados['Insatisfação'] = 0

In [ ]:
dados.loc[dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].notnull(), 'Qual o principal motivo da sua insatisfação com a empresa atual?'].apply(lambda x: 1 if 'Salário' in x else 0)

1       0
2       0
4       0
5       1
7       1
       ..
4238    0
4240    1
4264    0
4265    0
4270    1
Name: Qual o principal motivo da sua insatisfação com a empresa atual?, Length: 960, dtype: int64

In [ ]:
mask = dados['Qual o principal motivo da sua insatisfação com a empresa atual?'].notnull()
dados.loc[mask, 'Insatisfação'] = dados.loc[mask, 'Qual o principal motivo da sua insatisfação com a empresa atual?'].str.contains('Salário').astype(int)

In [ ]:
dados['Insatisfação'].value_counts()

Insatisfação
0    3897
1     374
Name: count, dtype: int64

In [ ]:
dados['NIVEL DE ENSINO'].value_counts()

NIVEL DE ENSINO
Graduação/Bacharelado         1510
Pós-graduação                 1314
Estudante de Graduação         613
Mestrado                       521
Doutorado ou Phd               191
Não tenho graduação formal     110
Prefiro não informar            12
Name: count, dtype: int64

In [ ]:
dados['NIVEL DE ENSINO'].apply(lambda x: 0 if x == 'Não tenho graduação formal' else
                                      (1 if x == 'Estudante de Graduação' else
                                      (2 if x == 'Graduação/Bacharelado' else
                                      (3 if x == 'Pós-graduação' else
                                      (4 if x == 'Mestrado' else
                                      (5 if x == 'Doutorado ou Phd' else
                                      (6 if x == 'Prefiro não informar' else -1)))))))

0       3
1       2
2       3
3       5
4       3
       ..
4266    2
4267    4
4268    4
4269    0
4270    2
Name: NIVEL DE ENSINO, Length: 4271, dtype: int64

In [ ]:
dados['NIVEL DE ENSINO'] = dados['NIVEL DE ENSINO']

In [ ]:
dados = dados[['IDADE','GENERO','nao_branca','tempo de expêriencia','Insatisfação','SETOR','REGIAO ONDE MORA', 'NIVEL DE ENSINO',
        'NUMERO DE FUNCIONARIOS','SALARIO','NOVO_NIVEL']]

In [ ]:
pd.get_dummies(dados, columns = ['GENERO', 'NOVO_NIVEL','SETOR','REGIAO ONDE MORA' ], drop_first = True)

,IDADE,nao_branca,tempo de expêriencia,Insatisfação,NIVEL DE ENSINO,NUMERO DE FUNCIONARIOS,SALARIO,GENERO_Masculino,GENERO_Prefiro não informar,NOVO_NIVEL_Pessoa Gestora,...,SETOR_Setor de Energia,SETOR_Tecnologia/Fábrica de Software,SETOR_Telecomunicação,SETOR_Varejo,SETOR_Área da Saúde,SETOR_Área de Consultoria,REGIAO ONDE MORA_Nordeste,REGIAO ONDE MORA_Norte,REGIAO ONDE MORA_Sudeste,REGIAO ONDE MORA_Sul
0,3.900000e+01,1,7,0,Pós-graduação,3000,11194.0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,3.200000e+01,1,1,0,Graduação/Bacharelado,3000,4695.0,True,False,True,...,False,False,False,False,False,False,False,True,False,False
2,5.300000e+01,0,10,0,Pós-graduação,3000,14202.0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2.700000e+01,0,NaN,0,Doutorado ou Phd,3000,15463.0,True,False,False,...,False,False,False,False,False,False,False,False,True,False
4,4.600000e+01,0,10,0,Pós-graduação,101,7733.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4266,2.600000e+01,0,7,0,Graduação/Bacharelado,3000,4329.0,True,False,False,...,False,True,False,False,False,False,False,False,True,False
4267,3.000000e+01,0,NaN,0,Mestrado,51,3758.0,False,False,False,...,False,False,False,False,False,True,False,False,True,False
4268,2.900000e+01,0,NaN,0,Mestrado,101,19607.0,True,False,True,...,False,False,False,False,False,False,False,False,True,False
4269,2.020548e+16,0,NaN,0,Não tenho graduação formal,1001,989.0,True,False,False,...,False,False,False,False,False,False,False,False,True,False
4270,2.400000e+01,0,NaN,1,Graduação/Bacharelado,501,3079.0,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit()